parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: mfw_db
    database_user: root
    database_password: 'samsung!@#'
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 7fe10749895dfdf6a31388c765a985857
    database_path: null
